# Screen style
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
set -g bell-action any

# Make tmux a historian
set -g history-limit 1000000

# Allow ctrl+b then 'r' to reload
unbind r
bind r \
    source-file ~/.tmux.conf \;\
    display 'Reloaded tmux config.'

# Enable mousey things - disable by default
set -g mouse on

# Toggle mouse on
bind m \
    set -g mouse on \;\
    display 'Mouse: ON'

# Toggle mouse off
bind M \
    set -g mouse off \;\
    display 'Mouse: OFF'

# Extra color?
set -g default-terminal "screen-256color"

# Use bash
#set-option -g default-shell bash

# pass through xterm keys
set -g xterm-keys on

# Also pass through extended keys
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Shift+PgUp / Shift+PgDown
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
bind -n S-Pageup copy-mode -eu \; send-keys -X page-up
bind -n S-Pagedown send-keys -X page-down

# Use vi compat mode for buffer
setw -g mode-keys vi

# Allow ctrl+b then + or - to
# maximize/restore split windows
unbind +
bind + new-window -d -n tmux-zoom 'clear && echo TMUX ZOOM && read' \; swap-pane -s tmux-zoom.0 \; select-window -t tmux-zoom
unbind -
bind - last-window \; swap-pane -s tmux-zoom.0 \; kill-window -t tmux-zoom

# Use the tmux-power(line) theme(s)
set -g @tmux_power_theme 'sky'
run-shell "~/tmux-power/tmux-power.tmux"
