#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# I HATE CORRECTION!
export DISABLE_CORRECTION="true"
unsetopt CORRECT
unsetopt correct
unsetopt correct_all

# Brace expansion
setopt BRACE_CCL

# Though I understand why this mark exists, I hate it.
PROMPT_EOL_MARK=" "

## Imported from original .bashrc
export TERM="xterm-256color"
export PATH=${PATH}:~/bin:/usr/local/bin:/usr/local/sbin
export LANG=en_US.utf8
export LESSCHARSET=utf-8
export PERL_UTF8_LOCALE=1 PERL_UNICODE=AS
alias tmux="tmux -2"

# Tmux
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

# Dircolors
if [ "$(uname -s)" = "Darwin" ]; then
  eval $(gdircolors ~/dircolors-solarized/dircolors.ansi-dark)
  alias ls="/usr/local/bin/gls --color=auto"
else
  eval $(dircolors ~/dircolors-solarized/dircolors.ansi-dark)
fi

# Password generator
alias pw="gopwgen -a"

# Kill the SC daemon
alias sckill="killall -9 scdaemon"
alias killsc="killall -9 scdaemon"

# Homeshick
source "$HOME/.homesick/repos/homeshick/homeshick.sh"
fpath=($HOME/.homesick/repos/homeshick/completions $fpath)

# Also hate this "safety" feature
setopt CLOBBER

# Super-local stuff that will only clog up the actual .zshrc
source "$HOME/.zshrc.extra"

# rbenv stuff
export PATH="$HOME/.rbenv/bin:$PATH"
which rbenv >/dev/null 2>&1 && eval "$(rbenv init -)"

PATH="/home/salvatore/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/salvatore/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/salvatore/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/salvatore/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/salvatore/perl5"; export PERL_MM_OPT;
